name: Push to Google Apps Script

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [closed]
    branches:
      - main
      - develop

jobs:
  clasp-push:
    # PRがマージされた場合または直接mainまたはdevelopにpushされた場合のみ実行
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Setup clasp
        run: |
          npm install -g @google/clasp
          mkdir -p ~/.config/clasp
          echo '${{ secrets.CLASP_TOKEN }}' > ~/.config/clasp/credentials.json

      - name: Push to Google Apps Script
        env:
          SCRIPT_ID: "13_EQB_VSmMqXgV-VCUyYFIS3pn0RvWVEhEm2KSfrMZ7K2sUxTYStC7WO"
        run: |
          # ローカルの.clasp.jsonの内容を確認
          cat .clasp.json || echo ".clasp.json not found"

          # スクリプトIDを設定
          echo '{"scriptId":"'"$SCRIPT_ID"'","rootDir":"."}' > .clasp.json

          # 認証ファイルを確認
          ls -la ~/.config/clasp/

          # クレデンシャルを使用してclasp push実行
          npm run push

      - name: Notify success
        if: success()
        run: echo "Successfully pushed to Google Apps Script at $(date)"

      - name: Notify failure
        if: failure()
        run: echo "Failed to push to Google Apps Script"
